### ISSUE TITLE
Ensure hex code formatting is consistent

### ISSUE THREAD

**Issue by ajsaraujo** [ajsaraujo/pablo#22]
When a color is randomly generated (e.g, when you create a new palette), it's hexcode is written in upper case. On the other hand, when you create a new color or edit an existing one, the hexcode is shown in *lower* case. Please ensure that all hexcodes are shown with the same casing.

![image](https://user-images.githubusercontent.com/34658414/110947947-898ee400-831f-11eb-9743-3850ab6d1e0f.png)

**Comment by lyndonjardine** [comment]
Hi, I'm starting work on this.
